services:

  # =====================
  # MYSQL
  # =====================
  mysql:
    image: mysql:8.0
    container_name: mysql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  # =====================
  # LARAVEL
  # =====================
  backend:
    image: php:8.2-apache
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./dishly-backend:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    ports:
      - "${BACKEND_PORT}:80"
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y libzip-dev unzip git &&
      docker-php-ext-install pdo pdo_mysql &&
      a2enmod rewrite &&
      php artisan migrate --force &&
      apache2-foreground
      "

  # =====================
  # ANGULAR
  # =====================
  frontend:
    image: node:20-alpine
    container_name: angular_app
    working_dir: /app
    volumes:
      - ./dishly-frontend:/app
    ports:
      - "${FRONTEND_PORT}:4200"
    command: >
      sh -c "
      npm install &&
      npm start -- --host 0.0.0.0
      "
    depends_on:
      - backend

volumes:
  mysql_data:
