services:

  # =====================
  # MYSQL
  # =====================
  mysql:
    image: mysql:latest
    container_name: mysql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - dishly-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # =====================
  # LARAVEL
  # =====================
  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./dishly-backend:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - dishly-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:${BACKEND_PORT}
    command: >
      bash -c "
      composer install --no-interaction --optimize-autoloader &&
      [ ! -f /var/www/html/.env ] && cp /var/www/html/.env.example /var/www/html/.env || true &&
      php artisan key:generate --no-interaction &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan migrate --force &&
      echo 'Server started' &&
      apache2-foreground
      "

  # =====================
  # ANGULAR
  # =====================
  frontend:
    image: node:latest
    container_name: angular_app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./dishly-frontend:/app
    ports:
      - "${FRONTEND_PORT}:4200"
    networks:
      - dishly-network
    command: >
      sh -c "
      npm install &&
      npm start -- --host 0.0.0.0 --port 4200 --poll 2000 --proxy-config proxy.conf.json
      "
    depends_on:
      - backend

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    command: start --all --config /etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - "./docker/ngrok.yml:/etc/ngrok.yml"
    ports:
      - "4040:4040"
    depends_on:
      - backend
      - frontend
    networks:
      - dishly-network

volumes:
  mysql_data:

networks:
  dishly-network:
    driver: bridge